# === ЭТАП 3 ===

In [1]:
import logging
import sys

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

log_file = logging.FileHandler('recommendations.log', mode='w')
log_file.setFormatter(logging.Formatter('%(asctime)s %(levelname)s %(message)s'))

console_out = logging.StreamHandler(sys.stdout)
console_out.setFormatter(logging.Formatter('%(message)s'))

logging.basicConfig(handlers=(log_file, console_out), level=logging.INFO)

# Загрузка данных

Если необходимо, то загружаем items.parquet, events.parquet.

In [10]:
items = pd.read_parquet('../data/items.parquet')
events = pd.read_parquet('../data/events.parquet')

events = events.merge(items.query('type == "track"')[['item_id', 'votes', 'rating']], on='item_id')

In [11]:
import sklearn.preprocessing

# перекодируем идентификаторы пользователей: 
# из имеющихся в последовательность 0, 1, 2, ...
user_encoder = sklearn.preprocessing.LabelEncoder()
user_encoder.fit(events['user_id'])
events['user_id_enc'] = user_encoder.transform(events['user_id'])

# перекодируем идентификаторы объектов: 
# из имеющихся в последовательность 0, 1, 2, ...
item_encoder = sklearn.preprocessing.LabelEncoder()
item_encoder.fit(items['item_id'])
items['item_id_enc'] = item_encoder.transform(items['item_id'])
events['item_id_enc'] = item_encoder.transform(events['item_id'])

# Разбиение данных

Разбиваем данные на тренировочную, тестовую выборки.

In [12]:
train_split_date = pd.to_datetime('2022-12-16').to_datetime64()

train_split_date_idx = events['started_at'] < train_split_date

events_train = events[train_split_date_idx]
events_test = events[~train_split_date_idx]

events_train.shape, events_test.shape

((9110491, 9), (3912838, 9))

In [13]:
# количество пользователей в train и test
users_train = events_train['user_id'].drop_duplicates()
users_test = events_test['user_id'].drop_duplicates()
# количество пользователей, которые есть и в train, и в test
common_users = set(users_train) & set(users_test)

len(users_train), len(users_test), len(common_users)

(1113710, 702781, 456576)

# Похожие

Рассчитаем похожие, они позже пригодятся для онлайн-рекомендаций.

In [14]:
import scipy
from implicit.als import AlternatingLeastSquares

def get_als_model(data, row, col):

    # создаём sparse-матрицу формата CSR 
    matrix = scipy.sparse.csr_matrix((
        data,
        (row, col)),
        dtype=np.int8)
    
    model = AlternatingLeastSquares(factors=50, iterations=10, regularization=0.05, random_state=0)
    model.fit(matrix) 
    
    return model

In [15]:
def get_similar_items(model, item_ids_enc, max_similar_items = 10):

    # получаем списки похожих объектов, используя ранее полученную ALS-модель
    # метод similar_items возвращает и сам объект, как наиболее похожий
    # этот объект мы позже отфильтруем, но сейчас запросим на 1 больше
    similar_items = model.similar_items(item_ids_enc, N=max_similar_items+1)

    # преобразуем полученные списки в табличный формат
    sim_item_item_ids_enc = similar_items[0]
    sim_item_scores = similar_items[1]

    similar_items = pd.DataFrame({
        "item_id_enc": item_ids_enc,
        "sim_item_id_enc": sim_item_item_ids_enc.tolist(), 
        "score": sim_item_scores.tolist()})
    similar_items = similar_items.explode(["sim_item_id_enc", "score"], ignore_index=True)

    # приводим типы данных
    similar_items["sim_item_id_enc"] = similar_items["sim_item_id_enc"].astype("int")
    similar_items["score"] = similar_items["score"].astype("float")

    # получаем изначальные идентификаторы
    similar_items["item_id_1"] = item_encoder.inverse_transform(similar_items["item_id_enc"])
    similar_items["item_id_2"] = item_encoder.inverse_transform(similar_items["sim_item_id_enc"])
    similar_items = similar_items.drop(columns=["item_id_enc", "sim_item_id_enc"])

    # убираем пары с одинаковыми объектами
    similar_items = similar_items.query("item_id_1 != item_id_2")
    
    return similar_items

In [16]:
def print_sim_items(item_id, similar_items):

    item_columns_to_use = ['item_id', 'name', 'votes', 'rating']
    
    item_id_1 = items.query('item_id == @item_id')[item_columns_to_use]
    display(item_id_1)
    
    si = similar_items.query('item_id_1 == @item_id')
    si = si.merge(items[item_columns_to_use].set_index('item_id'), left_on='item_id_2', right_index=True)
    display(si)

In [17]:
df_events = events_train[['rating', 'item_id', 'user_id']].rename(columns={'user_id': 'id'})
df_events['id'] = 'track_' + df_events['id'].astype(str)

df_items  = items[items['item_id'].isin(df_events['item_id'].unique())]

In [18]:
df_album = pd.DataFrame(df_items['album'].apply(eval).explode('album').tolist()).rename(columns={'track_id': 'item_id'})[['item_id', 'rating', 'id']]
df_album['id'] = 'album_' + df_album['id'].astype(str)

df_artist = pd.DataFrame(df_items['artist'].apply(eval).explode('artist').tolist()).rename(columns={'track_id': 'item_id'})[['item_id', 'rating', 'id']]
df_artist['id'] = 'artist_' + df_artist['id'].astype(str)

df_genre = pd.DataFrame(df_items['genre'].apply(eval).explode('genre').tolist()).rename(columns={'track_id': 'item_id'})[['item_id', 'rating', 'id']]
df_genre['id'] = 'genre_' + df_genre['id'].astype(str)

KeyError: 'album'

In [11]:
df = pd.concat([
    df_events,
    df_album,
    df_artist,
    df_genre
])

df['item_id_enc'] = item_encoder.transform(df['item_id'])

encoder = sklearn.preprocessing.LabelEncoder()
encoder.fit(df['id'])

df['id_enc'] = encoder.transform(df['id'])

In [19]:
df.query('item_id == 53404')

         rating  item_id            id  item_id_enc   id_enc
5615721   10.00    53404  track_592791          701   805626
5288603   10.00    53404  track_558272          701   774471
8829292   10.00    53404  track_931910          701  1111183
3422103   10.00    53404  track_361278          701   597309
5189866   10.00    53404  track_547834          701   765145
...         ...      ...           ...          ...      ...
4          7.67    53404  album_294912          701    20193
0          8.57    53404   artist_9262          701    58231
0          9.32    53404     genre_102          701    58713
1          8.20    53404      genre_14          701    58729
2          7.90    53404      genre_13          701    58727

[1135 rows x 5 columns]

In [13]:
als_model = get_als_model(df['rating'], df['id_enc'], df['item_id_enc'])
similar_items_users = get_similar_items(als_model, df['item_id_enc'].unique())

/home/mle-user/mle_projects/mle-project-sprint-4-v001/env_recsys_start/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 4 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████| 10/10 [00:46<00:00,  4.70s/it]

In [21]:
print_sim_items(35505245, similar_items_users)

        item_id        name  votes  rating
19154  35505245  I Got Love  99490    9.78

       score  item_id_1  item_id_2            name  votes  rating
34  0.914316   35505245   35780252     Заплаканная  15615    6.78
35  0.907032   35505245   35476145  Дико, например  15411    6.76
36  0.847588   35505245   35869002       Именно та   8747    6.04
37  0.845927   35505245   35554093    Yellow Light   1168    4.05
38  0.838624   35505245   34187641         Ламбада   6994    5.78
39  0.837808   35505245   34972337         Монетка  19185    7.06
40  0.832397   35505245   36519033            DLBM  14730    6.70
41  0.828502   35505245   35419758            Цепи   3563    5.06
42  0.826907   35505245   34362335        Танцуйте  24060    7.38
43  0.820018   35505245   35674500       Back2Leto   1935    4.48

In [14]:
raise

RuntimeError: No active exception to reraise

In [10]:
als_model = get_als_model(df_events['rating'], df_events['user_id_enc'], df_events['item_id_enc'])
similar_items_users = get_similar_items(als_model, df_events['item_id_enc'].unique())

/home/mle-user/mle_projects/mle-project-sprint-4-v001/env_recsys_start/lib/python3.10/site-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 4 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()
100%|██████████| 10/10 [00:44<00:00,  4.47s/it]

In [11]:
print_sim_items(787433, similar_items_users)

      item_id           name  votes  rating
4607   787433  Far From Over   1000    3.93

,score,item_id_1,item_id_2,name,votes,rating
2031994,0.937474,787433,1536466,Na Na Na (Na Na Na Na Na Na Na Na Na),7845,5.91
2031995,0.933368,787433,5706316,Stray Heart,1649,4.34
2031996,0.932947,787433,3480521,Everybody Talks,11366,6.36
2031997,0.931502,787433,6343854,Things We Lost in the Fire,3611,5.07
2031998,0.925710,787433,2216681,Get Up!,2036,4.53
2031999,0.923320,787433,2688595,Dreaming,1424,4.22
2032000,0.922266,787433,789166,Slam,1125,4.02
2032001,0.917639,787433,675181,Supernatural,1009,3.94
2032002,0.917027,787433,2178469,Sick,2176,4.59
2032003,0.916919,787433,4786230,Kill the DJ,3055,4.91
2032004,0.912859,787433,65990,Count Your Last Blessings,1801,4.42
2032005,0.911215,787433,670587,Quietly,2057,4.54
2032006,0.910977,787433,6699800,"Steady, As She Goes",2144,4.57
2032007,0.910723,787433,71308,Umbrella,3770,5.11
2032008,0.910294,787433,17196199,Guilty All The Same,1477,4.25
2032009,0.909192,787433,3738175,"For You, And Your Denial",1320,4.15
2032010,0.908108,787433,2330553,The Adventures of Rain Dance Maggie,1742,4.39
2032011,0.906048,787433,2189864,My Medicine,19506,7.08
2032012,0.902302,787433,403276,Know Your Enemy,2285,4.63
2032013,0.897554,787433,4789272,Still Swingin,1097,4.00
2032014,0.897553,787433,4254644,Let It Be,1369,4.18
2032015,0.896890,787433,418094,Starstrukk,3436,5.02
2032016,0.896617,787433,890846,Iridescent,1244,4.11
2032017,0.893716,787433,17448232,Mad World,1411,4.21
2032018,0.893454,787433,28115,All The Small Things,9491,6.14
2032019,0.892927,787433,772838,Give It All,3242,4.96
2032020,0.891732,787433,783139,Sell Your Soul,1341,4.17
2032021,0.891531,787433,4346135,Slim Pickens Does The Right Thing And Rides Th...,1751,4.39
2032022,0.889647,787433,928754,True Faith,1738,4.39
2032023,0.886877,787433,438408,¿Viva La Gloria? (Little Girl),3414,5.02
2032024,0.886516,787433,4981468,Without You,2058,4.54
2032025,0.886427,787433,37475,"Dance, Dance",13277,6.56
2032026,0.885851,787433,4304914,I’ll BE GONE,1304,4.14
2032027,0.885498,787433,9358290,My Songs Know What You Did In The Dark (Light ...,17668,6.95
2032028,0.884518,787433,9976316,Counting Stars,31521,7.79
2032029,0.882927,787433,4304918,POWERLESS,1212,4.08
2032030,0.881422,787433,9962683,The House of Wolves,1316,4.15
2032031,0.881285,787433,6689121,Blue Orchid,1360,4.18
2032032,0.881186,787433,3931702,BURN IT DOWN,18366,7.00
2032033,0.880734,787433,168657,Animals,4734,5.35
2032034,0.880550,787433,12287,Don't Lie,1997,4.51
2032035,0.878265,787433,789036,Sour Times,1028,3.95
2032036,0.878030,787433,10186902,Just One Yesterday,1882,4.46
2032037,0.877859,787433,8403762,Wretched And Divine,1128,4.03
2032038,0.877213,787433,202664,Dead Memories,7029,5.79
2032039,0.876764,787433,170166,Shadow of the Day,2060,4.54
2032040,0.876656,787433,2832224,Lonely Boy,7934,5.93
2032041,0.876513,787433,14490440,Do I Wanna Know?,8489,6.01
2032042,0.875872,787433,13217232,Hail to the King,1858,4.45
2032043,0.875268,787433,4304911,IN MY REMAINS,1629,4.33

In [ ]:
raise

In [12]:
df_genre = pd.DataFrame(df_items['genre'].apply(eval).explode('genre').tolist()).rename(columns={'track_id': 'item_id'})

genre_encoder = sklearn.preprocessing.LabelEncoder()
genre_encoder.fit(df_genre['id'])

df_genre['id_enc'] = genre_encoder.transform(df_genre['id'])
df_genre['item_id_enc'] = item_encoder.transform(df_genre['item_id'])

als_model = get_als_model(df_genre['rating'], df_genre['id_enc'], df_genre['item_id_enc'])
similar_items_genre = get_similar_items(als_model, df_genre['item_id_enc'].unique())

100%|██████████| 10/10 [00:01<00:00,  9.17it/s]

In [13]:
print_sim_items(787433, similar_items_genre)

      item_id           name  votes  rating
4607   787433  Far From Over   1000    3.93

,score,item_id_1,item_id_2,name,votes,rating
2031994,1.0,787433,58623710,Drowning,1367,4.18
2031995,1.0,787433,67110388,Рассвет,2835,4.83
2031996,1.0,787433,46156705,Me and the Devil,1142,4.04
2031997,1.0,787433,41535531,Despicable,6461,5.69
2031998,1.0,787433,39803206,Wicked Gonna Come,1541,4.28
2031999,1.0,787433,28431553,Line It Up,2309,4.64
2032000,1.0,787433,58682892,Ключи,1715,4.38
2032001,1.0,787433,52846288,Хорошие девочки,1455,4.24
2032002,1.0,787433,39412264,Гореть,3338,4.99
2032003,1.0,787433,38476760,Сядь и успокойся,1770,4.40
2032004,1.0,787433,135146,Better Than Drugs,1538,4.28
2032005,1.0,787433,84000375,Vacation,2197,4.60
2032006,1.0,787433,78863990,Blinding Lights,1228,4.10
2032007,1.0,787433,58682890,Чувства,1229,4.10
2032008,1.0,787433,53450690,Never Say Die,3149,4.94
2032009,1.0,787433,45976296,You Walk Away,2202,4.60
2032010,1.0,787433,45013995,"Say, Can You Hear",1257,4.11
2032011,1.0,787433,44215985,RISE,3103,4.92
2032012,1.0,787433,39850059,thoughts & prayers,9578,6.15
2032013,1.0,787433,37858566,Sugar Cane,1276,4.13
2032014,1.0,787433,4485062,Only Happy When It Rains,1255,4.11
2032015,1.0,787433,26654,Hate Me,1591,4.31
2032016,1.0,787433,75204190,Flames,1020,3.95
2032017,1.0,787433,73408302,Die Very Rough,4022,5.18
2032018,1.0,787433,71765178,I Met Sarah in the Bathroom,2385,4.67
2032019,1.0,787433,66622827,Плачем на рейвах,1209,4.08
2032020,1.0,787433,63241318,Dead Weight,1047,3.97
2032021,1.0,787433,58585558,Dirt,1327,4.16
2032022,1.0,787433,43081177,Coffee,5221,5.46
2032023,1.0,787433,43020290,Rockstar,1548,4.29
2032024,1.0,787433,11448404,A Day To Be Alone,1959,4.49
2032025,1.0,787433,6694947,Icky Thump,1466,4.24
2032026,1.0,787433,4981468,Without You,2058,4.54
2032027,1.0,787433,688818,The Power,11861,6.42
2032028,1.0,787433,629042,Scared,1024,3.95
2032029,1.0,787433,480973,Tell Me Why,2404,4.68
2032030,1.0,787433,71561755,Afterthought,2792,4.82
2032031,1.0,787433,62697960,Ты будешь гореть в аду,6491,5.70
2032032,1.0,787433,58623708,Sounds of Someday,1099,4.01
2032033,1.0,787433,49380309,Караван,2863,4.84
2032034,1.0,787433,48209718,Tokyo,1037,3.96
2032035,1.0,787433,41744437,Bad Things,1042,3.96
2032036,1.0,787433,35570099,The Way You Look at Me,1928,4.48
2032037,1.0,787433,31309740,Money Run Low,1086,4.00
2032038,1.0,787433,30183536,Famous,1533,4.28
2032039,1.0,787433,25545964,Who We Are,2807,4.82
2032040,1.0,787433,21825976,Release,1103,4.01
2032041,1.0,787433,19802080,This Night,2376,4.67
2032042,1.0,787433,19010630,First Time,1624,4.33
2032043,1.0,787433,16710459,Why'd You Bring a Shotgun to the Party,2124,4.56

In [14]:
df_artist = pd.DataFrame(df_items['artist'].apply(eval).explode('artist').tolist()).rename(columns={'track_id': 'item_id'})

artist_encoder = sklearn.preprocessing.LabelEncoder()
artist_encoder.fit(df_artist['id'])

df_artist['id_enc'] = artist_encoder.transform(df_artist['id'])
df_artist['item_id_enc'] = item_encoder.transform(df_artist['item_id'])

als_model = get_als_model(df_artist['rating'], df_artist['id_enc'], df_artist['item_id_enc'])
similar_items_artist = get_similar_items(als_model, df_artist['item_id_enc'].unique())

100%|██████████| 10/10 [00:01<00:00,  7.48it/s]

In [15]:
print_sim_items(787433, similar_items_artist)

      item_id           name  votes  rating
4607   787433  Far From Over   1000    3.93

,score,item_id_1,item_id_2,name,votes,rating
2031994,0.878050,787433,59580150,Не отпускай,3893,5.15
2031995,0.873845,787433,29133043,Пока боги спят,1369,4.18
2031996,0.870530,787433,41415351,Talk Is Cheap,2668,4.78
2031997,0.870463,787433,18700925,Breaking Skin,1056,3.97
2031998,0.869393,787433,68126848,Muffins In The Freezer,4376,5.27
2031999,0.868437,787433,25996084,Полетела душа,1525,4.27
2032000,0.857681,787433,632055,Heartbeat,1425,4.22
2032001,0.855658,787433,40351129,Феникс,1264,4.12
2032002,0.855346,787433,787430,Hell Yeah,6670,5.73
2032003,0.854704,787433,49923427,Monster,1949,4.49
2032004,0.853771,787433,85066110,Разучился,3333,4.99
2032005,0.851790,787433,87278383,Не для меня,1396,4.20
2032006,0.850140,787433,40668,Layla,2096,4.55
2032007,0.848883,787433,14409268,Deceive (feat. Sune Rose Wagner),1571,4.30
2032008,0.845367,787433,472391,In Your Hands,2303,4.64
2032009,0.843229,787433,53307488,Ransom,4911,5.39
2032010,0.841032,787433,43218493,Summer Cem,2292,4.63
2032011,0.838381,787433,2206419,The Look,3737,5.11
2032012,0.835598,787433,82875465,Ты не знаешь,1096,4.00
2032013,0.834010,787433,78580751,Hour,2161,4.58
2032014,0.833293,787433,24025990,Once In The Street,1574,4.30
2032015,0.831861,787433,5430482,Endless Summer,1123,4.02
2032016,0.830340,787433,39653923,Forever Young,1154,4.04
2032017,0.829590,787433,74398947,Lay All Your Love on Me,3043,4.90
2032018,0.827203,787433,436648,Walking in Circles,1379,4.19
2032019,0.825134,787433,41275906,Valhalla,1359,4.18
2032020,0.823993,787433,39727,Wasteland,1624,4.33
2032021,0.822964,787433,69619938,пустые речи,1834,4.43
2032022,0.821739,787433,98329324,LAst dAy oN EaRTh,1009,3.94
2032023,0.821025,787433,18221836,El Choclo,1254,4.11
2032024,0.820989,787433,46012861,Moon (And It Went Like),1479,4.25
2032025,0.820052,787433,32434989,Zero,3529,5.05
2032026,0.819364,787433,187878,La vita è,1055,3.97
2032027,0.819234,787433,26533736,Sing Sing Sing / It Don't Mean a Thing,1652,4.34
2032028,0.818745,787433,2923060,Love the Way You Lie,1526,4.28
2032029,0.817887,787433,63540440,Lamp,1396,4.20
2032030,0.817706,787433,63950303,Сердечко,1242,4.10
2032031,0.817453,787433,8798529,Mr. Saxobeat,2143,4.57
2032032,0.816909,787433,1526740,Young Blood,4376,5.27
2032033,0.816842,787433,96060,Man with the Hex,1866,4.45
2032034,0.816761,787433,63941017,Potions,1328,4.16
2032035,0.816346,787433,19044063,Up & Down,1803,4.42
2032036,0.816103,787433,75001842,"Da, Da, Da! Красивая душа",2543,4.73
2032037,0.816062,787433,19185621,Bei mir bist du Schön,2022,4.52
2032038,0.815767,787433,58287303,Тайна,1281,4.13
2032039,0.815756,787433,59709567,"ОХ, СЕЛО",2000,4.51
2032040,0.815344,787433,24827093,Roads,1486,4.25
2032041,0.815338,787433,48376041,Heard Somebody Whistle,1280,4.13
2032042,0.815108,787433,19897359,Ex's & Oh's,4074,5.19
2032043,0.814679,787433,93679500,Hell Shell Slowed & Reverb,1246,4.11

In [16]:
df_album = pd.DataFrame(df_items['album'].apply(eval).explode('album').tolist()).rename(columns={'track_id': 'item_id'})

album_encoder = sklearn.preprocessing.LabelEncoder()
album_encoder.fit(df_album['id'])

df_album['id_enc'] = album_encoder.transform(df_album['id'])
df_album['item_id_enc'] = item_encoder.transform(df_album['item_id'])

als_model = get_als_model(df_album['rating'], df_album['id_enc'], df_album['item_id_enc'])
similar_items_album = get_similar_items(als_model, df_album['item_id_enc'].unique())

100%|██████████| 10/10 [00:02<00:00,  4.79it/s]

In [17]:
print_sim_items(44104376, similar_items_album)

        item_id            name  votes  rating
24623  44104376  Niente da dire   1103    4.01

,score,item_id_1,item_id_2,name,votes,rating
1869507,1.000000,44104376,44104369,Fear for Nobody,9130,6.09
1869508,1.000000,44104376,44104365,L'altra dimensione,4953,5.40
1869509,1.000000,44104376,44104374,Are You Ready?,2861,4.84
1869511,1.000000,44104376,44104375,Close to the Top,1067,3.98
1869512,1.000000,44104376,44104370,Le parole lontane,3180,4.94
1869513,1.000000,44104376,44104364,New Song,5274,5.47
1869514,1.000000,44104376,44104372,Lasciami stare,1364,4.18
1869515,1.000000,44104376,39918391,Morirò da Re,7339,5.84
1869516,1.000000,44104376,43589177,Torna a casa,4068,5.19
1869517,0.673349,44104376,20690990,Дура,2244,4.61
1869518,0.671425,44104376,20690987,Дождь,1203,4.08
1869519,0.671254,44104376,20690985,Давай забудем лето,1794,4.41
1869520,0.670881,44104376,20690984,Безумно можно быть первым,16659,6.87
1869521,0.670843,44104376,20690991,Выпускной,1310,4.15
1869522,0.670521,44104376,20690988,Туманы,1099,4.01
1869523,0.658534,44104376,40053562,Сгораю,5878,5.59
1869524,0.640891,44104376,40053564,Сохрани мою речь,3067,4.91
1869525,0.635125,44104376,2183065,Jessica Kill,1949,4.49
1869526,0.634957,44104376,40053570,абв&эюя,1123,4.02
1869527,0.626539,44104376,2183063,Blood In My Eyes,1658,4.35
1869528,0.615756,44104376,60362363,Nostalgia,2917,4.86
1869529,0.615714,44104376,60362374,No,5286,5.47
1869530,0.615704,44104376,60362360,Another World,4257,5.24
1869531,0.615649,44104376,60362365,Where Are We?,1341,4.17
1869532,0.615644,44104376,60362358,Nightmare,13762,6.61
1869533,0.615569,44104376,60362381,Call Me,2509,4.72
1869534,0.615475,44104376,60362379,Closed,9185,6.10
1869535,0.613951,44104376,51752404,Glupye I Nenuzhnye,1269,4.12
1869536,0.610575,44104376,1232920,Crawl Through Knives,1114,4.02
1869537,0.605740,44104376,2169250,Screaming Bloody Murder,2570,4.74
1869538,0.602843,44104376,2238469,Come Clarity,1490,4.26
1869539,0.592469,44104376,40053554,Говорящие головы,3623,5.07
1869540,0.592434,44104376,1173604,I Like It Like That,7484,5.86
1869541,0.583875,44104376,59278290,Много кофеина,3105,4.92
1869542,0.583507,44104376,59278291,"Мама, я танцую",9605,6.16
1869543,0.583240,44104376,54937071,Deja Vu,2508,4.72
1869544,0.582251,44104376,59278288,Инея,1215,4.09
1869545,0.582185,44104376,59278285,Лава,1244,4.11
1869546,0.582104,44104376,59278283,Всем нашим,1580,4.30
1869547,0.582103,44104376,59278287,Красное – белое,2220,4.60
1869548,0.581761,44104376,2688595,Dreaming,1424,4.22
1869549,0.581247,44104376,33781892,After Dark,1267,4.12
1869550,0.578512,44104376,36610818,Whiskey Tango,6040,5.62
1869551,0.578044,44104376,33685346,Twist in My Sobriety,8060,5.95
1869552,0.577911,44104376,31903090,Deep Waters,6495,5.70
1869553,0.577909,44104376,31903097,Sleep No More,2250,4.62
1869554,0.577871,44104376,31903096,Only You,1116,4.02
1869555,0.577854,44104376,30966612,When We Were Lovers,1672,4.35
1869556,0.577262,44104376,20045340,Адреналин,2107,4.56
1869557,0.576449,44104376,2424422,Omen 3,2045,4.53

In [18]:
similar_items = pd.concat([
    similar_items_users,
    similar_items_genre,
    similar_items_artist,
    similar_items_album
])

In [19]:
similar_items['rank'] = similar_items.groupby(['item_id_1', 'item_id_2']).cumcount(ascending=False) + 1

In [20]:
similar_items.shape

(7972785, 4)

In [21]:
similar_items_1 = similar_items.groupby(['item_id_1', 'item_id_2']).agg(score=('score', 'sum'), rank=('rank', 'max')).reset_index()

similar_items_1['score'] = similar_items_1['score'] / 4
similar_items_1.sort_values('score', ascending=False, inplace=True)
similar_items_1['rank_score'] = similar_items_1.groupby(['item_id_1']).cumcount(ascending=True) + 1

In [26]:
similar_items_1.query('item_id_1 == 96366203')

         item_id_1  item_id_2     score  rank  rank_score
7644327   96366203   96366196  0.999775     4           1
7644325   96366203   96366194  0.749875     3           2
7644324   96366203   96366193  0.749759     3           3
7644331   96366203   96366204  0.749685     3           4
7644330   96366203   96366201  0.749670     3           5
...            ...        ...       ...   ...         ...
7644236   96366203   39166172  0.122798     1         154
7644193   96366203   21825965  0.122197     1         155
7644194   96366203   21825967  0.122197     1         156
7644195   96366203   21825969  0.122197     1         157
7644192   96366203   21825964  0.122197     1         158

[158 rows x 5 columns]

In [25]:
similar_items_1

         item_id_1  item_id_2     score  rank  rank_score
7644327   96366203   96366196  0.999775     4           1
7643688   96366196   96366203  0.999775     4           1
5392493   52974555   52974552  0.999663     4           1
2433562   24183553   24183545  0.999654     4           1
5392838   52974557   52974561  0.999651     4           1
...            ...        ...       ...   ...         ...
1964900   18006276   31998691  0.072178     1         196
1964917   18006276   39450215  0.072177     1         197
1964823   18006276   14380434  0.072172     1         198
1964857   18006276   19673912  0.072172     1         199
1964914   18006276   39248259  0.072172     1         200

[7686350 rows x 5 columns]