In [1]:
import logging
import sys

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

In [3]:
pd.read_parquet('../services/data/final_recommendations.parquet')

,user_id,item_id,personal_score,personal_genre_score,similar_score,similar_genre_score,cb_score,rank
138,4,75944934,0.014600,0.040307,NaN,NaN,0.370511,1
146,4,78824202,0.015637,0.048444,NaN,NaN,0.356566,2
155,4,86710605,0.016279,0.052624,NaN,NaN,0.355923,3
157,4,89439864,0.013799,0.039373,NaN,NaN,0.352473,4
154,4,86081547,0.013618,0.035134,NaN,NaN,0.351049,5
...,...,...,...,...,...,...,...,...
35666150,1374574,562,0.000000,0.000000,NaN,NaN,0.329397,6
35666151,1374574,859,0.000000,0.000000,NaN,NaN,0.329397,7
35666152,1374574,861,0.000000,0.000000,NaN,NaN,0.329397,8
35666153,1374574,867,0.000000,0.000000,NaN,NaN,0.329397,9
35666154,1374574,966,0.000000,0.000000,NaN,NaN,0.329397,10

In [4]:
pd.read_parquet('../services/data/top_popular.parquet')

        item_id  users  rating  users_norm  rating_norm     score
39278  93126179  23571    8.75    1.000000     0.794069  0.794069
37443  81848875  17176    9.04    0.728681     0.841845  0.613436
37640  83063895  15186    9.07    0.644251     0.846787  0.545544
33163  65851540  12769    9.52    0.541706     0.920923  0.498869
37912  84382282  14336    8.90    0.608188     0.818781  0.497973
...         ...    ...     ...         ...          ...       ...
34035  68938482   4675    8.24    0.198303     0.710049  0.140805
25038  45130892   4384    8.52    0.185957     0.756178  0.140616
17054  32182642   4422    8.47    0.187569     0.747941  0.140290
16290  31078723   4875    8.04    0.206788     0.677100  0.140016
7901    6705392   3623    9.43    0.153670     0.906096  0.139240

[100 rows x 6 columns]

In [5]:
pd.read_parquet('../services/data/similar_items.parquet')

           score  item_id_1  item_id_2
1       0.987362      99262     855241
2       0.986703      99262     812255
3       0.985279      99262     646679
4       0.983790      99262   18006276
5       0.983159      99262     119578
...          ...        ...        ...
438279  0.997471     732625      41573
438280  0.997429     732625     328679
438281  0.997408     732625     354357
438282  0.997182     732625    8169973
438283  0.997165     732625    3599234

[398440 rows x 3 columns]